### ISSUE TITLE
Error while initializing Argus

### ISSUE THREAD

**Issue by abhishekBansal** [moldedbits/argus-android#22]
> Failed to auto initialize the Facebook SDK
>                                                                                      A valid Facebook app id must be set in the AndroidManifest.xml or set by calling FacebookSdk.setApplicationId before initializing the sdk.
>                                                                                          at com.facebook.FacebookSdk.sdkInitialize(FacebookSdk.java:275)
>                                                                                          at com.facebook.FacebookSdk.sdkInitialize(FacebookSdk.java:231)
>                                                                                          at com.facebook.internal.FacebookInitProvider.onCreate(FacebookInitProvider.java:20)
>                                                                                          at android.content.ContentProvider.attachInfo(ContentProvider.java:1801)
>                                                                                          at android.content.ContentProvider.attachInfo(ContentProvider.java:1776)
>                                                                                          at android.app.ActivityThread.installProvider(ActivityThread.java:5501)
>                                                                                          at android.app.ActivityThread.installContentProviders(ActivityThread.java:5053)
>                                                                                          at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4993)
>                                                                                          at android.app.ActivityThread.-wrap1(ActivityThread.java)
>                                                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1573)
>                                                                                          at android.os.Handler.dispatchMessage(Handler.java:111)
>                                                                                          at android.os.Looper.loop(Looper.java:207)
>                                                                                          at android.app.ActivityThread.main(ActivityThread.java:5811)
>                                                                                          at java.lang.reflect.Method.invoke(Native Method)
>                                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:791)
>                                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:681)

**Comment by shishanksingh2015** [comment]
@abhishekBansal  it is done please check if it still exists,thanks
